cmake_minimum_required(VERSION 3.8)
project(hik_tem)
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(sensor_msgs REQUIRED)
find_package(message_interface REQUIRED)
find_package(OpenCV REQUIRED)
add_executable(hik_camera_node src/hik_camera.cpp)
target_compile_features(hik_camera_node PUBLIC cxx_std_17)
target_include_directories(hik_camera_node PRIVATE include ${OpenCV_INCLUDE_DIRS})
target_link_directories(hik_camera_node PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/lib)
target_link_libraries(hik_camera_node hcnetsdk ${OpenCV_LIBS})
ament_target_dependencies(hik_camera_node rclcpp sensor_msgs message_interface)
target_link_libraries(hik_camera_node message_interface::message_interface__rosidl_typesupport_cpp)
set_target_properties(hik_camera_node PROPERTIES INSTALL_RPATH "$ORIGIN/../hik_tem")
install(TARGETS hik_camera_node DESTINATION lib/${PROJECT_NAME})
install(PROGRAMS scripts/ptz_ctrl.py DESTINATION lib/${PROJECT_NAME})
install(DIRECTORY launch DESTINATION share/${PROJECT_NAME})
install(DIRECTORY lib/ DESTINATION lib/${PROJECT_NAME})
ament_package()
