<?xml version="1.0"?><package format="3"><name>hik_tem</name><version>2.0.0</version><description>HCNetSDK ROS 2 driver for Hikvision visible and bi-spectrum cameras.</description><maintainer email="li012@todo.todo">handong</maintainer><license>Proprietary</license><buildtool_depend>ament_cmake</buildtool_depend><depend>rclcpp</depend><depend>sensor_msgs</depend><depend>message_interface</depend><depend>opencv</depend><export><build_type>ament_cmake</build_type></export></package>
