<?xml version="1.0"?><package format="3"><name>opencpn2ros</name><version>2.0.0</version><description>OpenCPN UDP bridges for ROS 2.</description><maintainer email="li012@todo.todo">handong</maintainer><license>BSD-3-Clause</license><buildtool_depend>ament_python</buildtool_depend><exec_depend>rclpy</exec_depend><exec_depend>nmea_msgs</exec_depend><exec_depend>message_interface</exec_depend><export><build_type>ament_python</build_type></export></package>
