cmake_minimum_required(VERSION 3.8)
project(imu)
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(message_interface REQUIRED)
add_executable(imu src/IMU.cpp)
target_compile_features(imu PUBLIC cxx_std_17)
target_include_directories(imu PRIVATE include)
ament_target_dependencies(imu rclcpp message_interface)
target_link_libraries(imu message_interface::message_interface__rosidl_typesupport_cpp)
install(TARGETS imu DESTINATION lib/${PROJECT_NAME})
install(DIRECTORY launch DESTINATION share/${PROJECT_NAME})
ament_package()
