cmake_minimum_required(VERSION 3.8)
project(ros_project_pc_to_image)
find_package(ament_cmake REQUIRED)
find_package(ament_index_cpp REQUIRED)
find_package(rclcpp REQUIRED)
find_package(sensor_msgs REQUIRED)
find_package(cv_bridge REQUIRED)
find_package(pcl_conversions REQUIRED)
find_package(PCL REQUIRED)
find_package(OpenCV REQUIRED)
add_executable(ros_project_pc_to_image src/project.cpp)
target_compile_features(ros_project_pc_to_image PUBLIC cxx_std_17)
target_include_directories(ros_project_pc_to_image PRIVATE ${PCL_INCLUDE_DIRS} ${OpenCV_INCLUDE_DIRS})
target_link_libraries(ros_project_pc_to_image ${PCL_LIBRARIES} ${OpenCV_LIBS})
ament_target_dependencies(ros_project_pc_to_image ament_index_cpp rclcpp sensor_msgs cv_bridge pcl_conversions)
install(TARGETS ros_project_pc_to_image DESTINATION lib/${PROJECT_NAME})
install(DIRECTORY cfg DESTINATION share/${PROJECT_NAME})
ament_package()
