<?xml version="1.0"?><package format="3"><name>ros_project_pc_to_image</name><version>2.0.0</version><description>Point cloud to camera projection.</description><maintainer email="root@todo.todo">handong</maintainer><license>BSD-3-Clause</license><buildtool_depend>ament_cmake</buildtool_depend><depend>ament_index_cpp</depend><depend>rclcpp</depend><depend>sensor_msgs</depend><depend>cv_bridge</depend><depend>pcl_conversions</depend></package>
