<?xml version="1.0"?>
<package format="3">
  <name>mess_sync</name><version>2.0.0</version>
  <description>Approximate camera and point cloud synchronizer.</description>
  <maintainer email="li012@todo.todo">handong</maintainer><license>BSD-3-Clause</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend><depend>sensor_msgs</depend><depend>pcl_conversions</depend>
</package>
